---
title: "Topic clustering Report"
output: html_document
---

# トピック文書クラスタリング結果

#### 注

* `Topic Parameter`は文書をクラスタリングしたトピック数を示しています。
* `docs`が各クラスタに属する文書数を示します
* `sentences`はクラスタ内で代表的な文を示します
* `words`はクラスタ内のトピック的な単語です。
* `topicId`には特に深い意味はありません


```{r, header, echo=FALSE, warning=FALSE}
library(xtable)
library(plyr)
```


```{r, funcs, echo=FALSE, warning=FALSE, results='asis'}
showResultInClustering <- function(topicParameter, results_frame){
  print(sprintf('Topic Parameter %s', topicParameter))
  frameInClustering <- results_frame[results_frame$topicParameter==topicParameter, ]
  frameInClustering$topicParameter <- as.integer(frameInClustering$topicParameter)
  frameInClustering$topicId <- as.integer(frameInClustering$topicId)
  frameInClustering$docs <- as.integer(frameInClustering$docs)
  
  frameInClustering <- frameInClustering[order(frameInClustering$docs, decreasing = T), ]
  frameInClustering$rank <- 1:nrow(frameInClustering)
  frameInClustering <- frameInClustering[, c("rank", "docs", "topicId", "sentences", "words")]
  
  xtable::print.xtable(xtable::xtable(frameInClustering), type = 'html', include.rownames = F)

}
```

```{r, echo=FALSE, warning=FALSE, results='asis'}
for (topicParameter in unique(results_frame$topicParameter)){
  showResultInClustering(topicParameter, results_frame)
}
cat("<style type=\"text/css\"> table {border-collapse: collapse;} table,td,th{ border:solid 1px; } td{text-align:right} th{text-align:center} </style>\n")
```
